baseURL = "http://example.org/"
languageCode = "en-us"
title = "GeoScripting"
theme = "ananke"

[params]
  featured_image = "img/rainier.jpeg"
  custom_css = ["css/styles.css"]
  rss = ""
  linkedin = "https://www.linkedin.com/in/ericksonjared"
  github = "https://github.com/jericks"
  background_color_class = "bg-dark-blue"